import type { ProjectBaseMetadata, ProjectRecord, ProjectSnapshot } from "../runtime/runtime";
import { getDemoStorageProjectId } from "./demoService";
import type { DemoProjectDefinition, DemoProjectId } from "./types";

const FIXTURE_VERSION = 1;

const buildProject = (
  id: DemoProjectId,
  seed: Omit<ProjectRecord, "id">,
): ProjectRecord => ({
  ...seed,
  id: getDemoStorageProjectId(id, FIXTURE_VERSION),
  tracks: { ...seed.tracks },
});

const buildSnapshot = (
  id: DemoProjectId,
  updatedAt: string,
  baseMeta: ProjectBaseMetadata,
  tools: Record<string, unknown>,
): ProjectSnapshot => ({
  projectId: getDemoStorageProjectId(id, FIXTURE_VERSION),
  clientId: "",
  version: 1,
  updatedAt,
  baseMeta,
  tools,
});

const casaLaderaId: DemoProjectId = "casa-ladera";
const casaLaderaUpdatedAt = "2026-07-15T15:00:00.000Z";
const casaLaderaTracks = { diseno: true, construccion: true, seguimiento: false };

const casaLadera: DemoProjectDefinition = {
  id: casaLaderaId,
  version: FIXTURE_VERSION,
  title: "Casa Ladera",
  subtitle: "Vivienda familiar · Propuesta integral de diseño",
  clientName: "Familia Ramírez",
  location: "Lima",
  area: 240,
  currency: "PEN",
  displayStatus: "Propuesta",
  duplicateStatus: "Propuesta",
  tracks: casaLaderaTracks,
  project: buildProject(casaLaderaId, {
    name: "Casa Ladera",
    type: "Vivienda unifamiliar",
    location: "Lima",
    tracks: casaLaderaTracks,
    archived: false,
    commercialStatus: "Propuesta",
    createdAt: casaLaderaUpdatedAt,
    updatedAt: casaLaderaUpdatedAt,
  }),
  snapshot: buildSnapshot(
    casaLaderaId,
    casaLaderaUpdatedAt,
    {
      client: "Familia Ramírez",
      projectName: "Casa Ladera",
      location: "Lima",
      code: "PR-CL-001",
      currency: "PEN",
    },
    {
      "calc.step": 3,
      "calc.fe": "2026-07-15",
      "calc.ti": "Vivienda",
      "calc.et": "Proyecto arquitectónico",
      "calc.ar": "240",
      "calc.mo": "Suma alzada",
      "calc.ig": true,
      "calc.co": "Media",
      "calc.ur": "Normal",
      "calc.tc": "Particular",
      "calc.mg": 10,
      "calc.dc": 0,
      "calc.rd": 50,
      "calc.rx": 2,
      "calc.vx": 4,
      "calc.nx": 3,
      "matrix.fe": "2026-07-15",
      "matrix.paq": "Proyecto arquitectónico",
      "matrix.items": [
        { id: "CL-MX-01", paquete: "Proyecto arquitectónico", etapa: "Levantamiento", entregable: "Ficha de requerimientos y programa familiar", formato: "PDF", cantidad: "1", notas: "Programa validado con la Familia Ramírez.", on: true },
        { id: "CL-MX-02", paquete: "Proyecto arquitectónico", etapa: "Anteproyecto", entregable: "Propuesta de implantación y distribución", formato: "PDF", cantidad: "2 alternativas", notas: "Incluye evaluación de vistas y asoleamiento.", on: true },
        { id: "CL-MX-03", paquete: "Proyecto arquitectónico", etapa: "Anteproyecto", entregable: "Plantas, cortes y elevaciones preliminares", formato: "PDF", cantidad: "1 set", notas: "Escala 1:100.", on: true },
        { id: "CL-MX-04", paquete: "Proyecto arquitectónico", etapa: "Anteproyecto", entregable: "Vistas 3D exteriores e interiores", formato: "JPG/PDF", cantidad: "5", notas: "Imágenes de validación de materialidad.", on: true },
        { id: "CL-MX-05", paquete: "Proyecto arquitectónico", etapa: "Desarrollo", entregable: "Plantas, cortes y elevaciones desarrolladas", formato: "PDF", cantidad: "1 paquete", notas: "Documentación coordinada de arquitectura.", on: true },
        { id: "CL-MX-06", paquete: "Proyecto arquitectónico", etapa: "Desarrollo", entregable: "Detalles arquitectónicos críticos", formato: "PDF", cantidad: "12", notas: "Encuentros de fachada, escaleras y carpinterías.", on: true },
        { id: "CL-MX-07", paquete: "Proyecto arquitectónico", etapa: "Expediente", entregable: "Memoria descriptiva arquitectónica", formato: "PDF", cantidad: "1", notas: "Documento final para coordinación.", on: true },
      ],
      "excl.fe": "2026-07-15",
      "excl.resp": "Arq. Lucía Vega",
      "excl.items": [
        { id: "CL-EX-01", cat: "Exclusiones generales", item: "Trámites y licencias", estado: "Excluido", mostrar: true, texto: "No incluye gestión municipal, tasas ni derechos de licencia." },
        { id: "CL-EX-02", cat: "Exclusiones generales", item: "Especialidades", estado: "Excluido", mostrar: true, texto: "Estructuras e instalaciones se coordinan con consultores del cliente." },
        { id: "CL-EX-03", cat: "Exclusiones específicas", item: "Paisajismo", estado: "Excluido", mostrar: true, texto: "El diseño detallado de paisaje no forma parte del alcance base." },
        { id: "CL-EX-04", cat: "Supuestos técnicos", item: "Levantamiento disponible", estado: "Supuesto", mostrar: true, texto: "Se considera confiable la información topográfica entregada por el cliente." },
        { id: "CL-EX-05", cat: "Supuestos comerciales", item: "Rondas de revisión", estado: "Supuesto", mostrar: true, texto: "Se incluyen dos rondas de comentarios por etapa." },
        { id: "CL-EX-06", cat: "Supuestos de plazo", item: "Aprobación por etapa", estado: "Supuesto", mostrar: true, texto: "El cronograma supone aprobaciones del cliente en un máximo de tres días hábiles." },
      ],
      "cron.fe": "2026-07-15",
      "cron.inicio": "2026-08-03",
      "cron.etapas": [
        { id: "lev", label: "Levantamiento", color: "#2471A3", semanas: 1, activa: true },
        { id: "ant", label: "Anteproyecto", color: "#1E8449", semanas: 3, activa: true },
        { id: "des", label: "Desarrollo", color: "#B7950B", semanas: 4, activa: true },
        { id: "exp", label: "Expediente técnico", color: "#BA4A00", semanas: 3, activa: true },
        { id: "sup", label: "Supervisión / Obra", color: "#6C3483", semanas: 12, activa: false },
      ],
      "cron.honorario": "19450",
      "cron.nota": "Plazos sujetos a aprobación de cada etapa y entrega oportuna de información de especialidades.",
      "cron.hitosCobro": [
        { id: "adelanto", label: "Adelanto", pct: 50, when: "Al aprobar la propuesta", checked: true },
        { id: "anteproyecto", label: "Anteproyecto", pct: 25, when: "Con la aprobación del anteproyecto", checked: false },
        { id: "entrega", label: "Entrega", pct: 25, when: "Con la entrega del expediente", checked: false },
      ],
      "brief.step": 4,
      "brief.tipoP": "Arquitectura nueva",
      "brief.areaTe": "420",
      "brief.areaEx": "0",
      "brief.presup": "720000",
      "brief.feObj": "2026-12-18",
      "brief.estado": "Brief confirmado",
      "brief.resp": "Arq. Lucía Vega",
      "brief.feLev": "2026-07-10",
      "brief.rows": [
        { id: 101, zona: "Pública", espacio: "Sala - comedor", cantidad: "1", areaUnit: "42", usuarios: "8", relacion: "Directa", prioridad: "Alta", obs: "Integrada a la terraza." },
        { id: 102, zona: "Pública", espacio: "Cocina", cantidad: "1", areaUnit: "18", usuarios: "4", relacion: "Directa", prioridad: "Alta", obs: "Isla central." },
        { id: 103, zona: "Pública", espacio: "Estudio", cantidad: "1", areaUnit: "14", usuarios: "2", relacion: "Indirecta", prioridad: "Media", obs: "Uso flexible como cuarto de visitas." },
        { id: 104, zona: "Privada", espacio: "Dormitorio principal", cantidad: "1", areaUnit: "28", usuarios: "2", relacion: "Directa", prioridad: "Alta", obs: "Incluye baño y vestidor." },
        { id: 105, zona: "Privada", espacio: "Dormitorio secundario", cantidad: "2", areaUnit: "16", usuarios: "1", relacion: "Directa", prioridad: "Alta", obs: "Iluminación natural." },
        { id: 106, zona: "Privada", espacio: "Baño", cantidad: "3", areaUnit: "6", usuarios: "2", relacion: "Directa", prioridad: "Alta", obs: "Uno principal y dos compartidos." },
        { id: 107, zona: "Servicio", espacio: "Lavandería", cantidad: "1", areaUnit: "10", usuarios: "2", relacion: "Indirecta", prioridad: "Media", obs: "Con patio de servicio." },
        { id: 108, zona: "Servicio", espacio: "Dormitorio de servicio", cantidad: "1", areaUnit: "12", usuarios: "1", relacion: "Indirecta", prioridad: "Baja", obs: "Cercano a lavandería." },
        { id: 109, zona: "Común", espacio: "Circulaciones y escalera", cantidad: "1", areaUnit: "28", usuarios: "8", relacion: "Directa", prioridad: "Alta", obs: "Con iluminación cenital." },
        { id: 110, zona: "Exterior", espacio: "Terraza techada", cantidad: "1", areaUnit: "24", usuarios: "8", relacion: "Directa", prioridad: "Alta", obs: "Con vista al jardín." },
        { id: 111, zona: "Servicio", espacio: "Depósito", cantidad: "1", areaUnit: "6", usuarios: "1", relacion: "Indirecta", prioridad: "Baja", obs: "Almacenamiento general." },
        { id: 112, zona: "Pública", espacio: "Hall de ingreso", cantidad: "1", areaUnit: "8", usuarios: "4", relacion: "Directa", prioridad: "Media", obs: "Ingreso protegido." },
      ],
      "brief.matrix": {
        "101-102": "D",
        "102-101": "D",
        "104-105": "I",
        "105-104": "I",
      },
      "brief.norm": { normAplicable: "RNE y parámetros urbanísticos vigentes", retiros: "Frontal 5 m; laterales según certificado", altura: "Máximo 3 pisos", parametros: "Uso residencial", servidumbres: "Sin servidumbres reportadas", restricLote: "Pendiente validar linderos", condComite: "Revisión del comité de condominio" },
      "brief.tec": { estadoExist: "Lote sin edificación", limitEstructural: "Por definir con ingeniero estructural", instalaciones: "Puntos de conexión en lindero", accesos: "Acceso vehicular por frente sur", restricObra: "Horario regulado por condominio" },
      "brief.pref": { materialidad: "Piedra clara, madera y concreto visto", estilo: "Contemporáneo cálido", prioFunc: "Vida familiar y conexión con terraza", prefAmbiental: "Iluminación natural y ventilación cruzada", deseados: "Terraza, jardín, cocina integrada y estudio", noDeseados: "Circulaciones oscuras y espacios residuales", referencias: "Arquitectura costera contemporánea", obsAbiertas: "Validar piscina y área de parrilla en anteproyecto" },
    },
  ),
  tourSteps: [
    { id: "casa-programa", title: "Programa familiar", description: "Revisa cómo las necesidades de la familia se convierten en ambientes, áreas y relaciones.", toolId: "brief", track: "construccion" },
    { id: "casa-honorarios", title: "Honorarios calculados", description: "Explora la propuesta económica para 240 m² y sus factores de ajuste.", toolId: "calc", track: "diseno" },
    { id: "casa-entregables", title: "Entregables claros", description: "Comprueba qué recibe el cliente en cada etapa del servicio.", toolId: "matrix", track: "diseno" },
    { id: "casa-alcance", title: "Alcance protegido", description: "Identifica exclusiones y supuestos antes de presentar la propuesta.", toolId: "excl", track: "diseno" },
    { id: "casa-cronograma", title: "Cronograma y cobros", description: "Relaciona etapas, duración e hitos de pago en una sola vista.", toolId: "cron", track: "diseno" },
  ],
  highlights: ["Programa de vivienda", "Honorarios y propuesta", "Matriz de entregables", "Exclusiones", "Cronograma por etapas"],
};

const cafeNereaId: DemoProjectId = "cafe-nerea";
const cafeNereaUpdatedAt = "2026-07-16T16:00:00.000Z";
const cafeNereaTracks = { diseno: true, construccion: true, seguimiento: false };

const cafeNerea: DemoProjectDefinition = {
  id: cafeNereaId,
  version: FIXTURE_VERSION,
  title: "Café Nerea",
  subtitle: "Interiorismo comercial · Apertura en 8 semanas",
  clientName: "Nerea Café S.A.C.",
  location: "Barranco, Lima",
  area: 118,
  currency: "PEN",
  displayStatus: "Propuesta",
  duplicateStatus: "Propuesta",
  tracks: cafeNereaTracks,
  project: buildProject(cafeNereaId, {
    name: "Café Nerea",
    type: "Interiorismo comercial",
    location: "Barranco, Lima",
    tracks: cafeNereaTracks,
    archived: false,
    commercialStatus: "Propuesta",
    createdAt: cafeNereaUpdatedAt,
    updatedAt: cafeNereaUpdatedAt,
  }),
  snapshot: buildSnapshot(
    cafeNereaId,
    cafeNereaUpdatedAt,
    {
      client: "Nerea Café S.A.C.",
      projectName: "Café Nerea",
      location: "Barranco, Lima",
      code: "PR-CN-008",
      currency: "PEN",
    },
    {
      "brief.step": 4,
      "brief.tipoP": "Interiorismo",
      "brief.areaTe": "118",
      "brief.areaEx": "118",
      "brief.presup": "245000",
      "brief.feObj": "2026-09-14",
      "brief.estado": "Brief confirmado",
      "brief.resp": "Arq. Elena Mora",
      "brief.feLev": "2026-07-16",
      "brief.rows": [
        { id: 201, zona: "Comercial", espacio: "Salón de clientes", cantidad: "1", areaUnit: "44", usuarios: "42", relacion: "Directa", prioridad: "Alta", obs: "Capacidad objetivo: 42 personas sentadas." },
        { id: 202, zona: "Comercial", espacio: "Barra de atención", cantidad: "1", areaUnit: "16", usuarios: "6", relacion: "Directa", prioridad: "Alta", obs: "Caja, vitrina, espresso y punto de recojo." },
        { id: 203, zona: "Servicio", espacio: "Cocina de producción", cantidad: "1", areaUnit: "20", usuarios: "6", relacion: "Directa", prioridad: "Alta", obs: "Flujo separado de preparación y lavado." },
        { id: 204, zona: "Servicio", espacio: "Lavado y back of house", cantidad: "1", areaUnit: "8", usuarios: "3", relacion: "Directa", prioridad: "Alta", obs: "Salida directa a ruta de servicio." },
        { id: 205, zona: "Servicio", espacio: "Almacén seco y frío", cantidad: "1", areaUnit: "6", usuarios: "2", relacion: "Indirecta", prioridad: "Media", obs: "Acceso controlado desde cocina." },
        { id: 206, zona: "Servicio", espacio: "SS.HH. clientes", cantidad: "2", areaUnit: "4", usuarios: "1", relacion: "Indirecta", prioridad: "Alta", obs: "Validar accesibilidad." },
        { id: 207, zona: "Servicio", espacio: "SS.HH. personal", cantidad: "1", areaUnit: "3", usuarios: "1", relacion: "Indirecta", prioridad: "Media", obs: "Uso exclusivo del equipo." },
        { id: 208, zona: "Común", espacio: "Circulación y espera", cantidad: "1", areaUnit: "13", usuarios: "10", relacion: "Directa", prioridad: "Alta", obs: "No interferir con la cola de atención." },
      ],
      "brief.matrix": {
        "201-202": "D",
        "202-201": "D",
        "202-203": "D",
        "203-202": "D",
        "203-204": "D",
        "204-203": "D",
        "201-208": "D",
        "208-201": "D",
      },
      "brief.norm": { normAplicable: "RNE, seguridad y normativa sanitaria", retiros: "No aplica a local interior", altura: "Altura libre existente por verificar", parametros: "Uso comercial compatible por confirmar", servidumbres: "Sin información", restricLote: "Local en inmueble existente", condComite: "Aprobación de la junta del inmueble pendiente" },
      "brief.tec": { estadoExist: "Local comercial por levantar", limitEstructural: "No intervenir elementos estructurales", instalaciones: "Coordinación MEP pendiente", accesos: "Ingreso público por avenida y servicio lateral", restricObra: "Horario de obra por confirmar con administración" },
      "brief.pref": { materialidad: "Madera oscura, acero y cerámica artesanal", estilo: "Contemporáneo barranquino", prioFunc: "Velocidad de servicio y rotación de mesas", prefAmbiental: "Luz cálida y control acústico", deseados: "Barra protagonista, vitrina visible y mesas flexibles", noDeseados: "Cruce entre clientes, insumos y residuos", referencias: "Cafés de especialidad de escala barrial", obsAbiertas: "Faltan levantamiento, coordinación de especialidades, equipamiento de cocina, licencias, identidad gráfica y proveedores." },
      "matrix.fe": "2026-07-16",
      "matrix.paq": "Anteproyecto",
      "matrix.items": [
        { id: "CN-MX-01", paquete: "Anteproyecto", etapa: "Levantamiento", entregable: "Brief operativo y programa de áreas", formato: "PDF", cantidad: "1", notas: "Incluye capacidad, flujos, barra, cocina y servicio.", on: true },
        { id: "CN-MX-02", paquete: "Anteproyecto", etapa: "Levantamiento", entregable: "Levantamiento arquitectónico del local", formato: "DWG/PDF", cantidad: "1", notas: "Pendiente de ejecución y validación en sitio.", notaPersonalizada: "Información faltante", on: true },
        { id: "CN-MX-03", paquete: "Anteproyecto", etapa: "Anteproyecto", entregable: "Layout de salón, barra y cocina", formato: "PDF", cantidad: "2 alternativas", notas: "Evaluación de capacidad y rutas de servicio.", on: true },
        { id: "CN-MX-04", paquete: "Anteproyecto", etapa: "Anteproyecto", entregable: "Moodboard y criterios de materialidad", formato: "PDF", cantidad: "1", notas: "Base visual para coordinar la identidad del local.", on: true },
        { id: "CN-MX-05", paquete: "Anteproyecto", etapa: "Anteproyecto", entregable: "Vistas 3D de áreas clave", formato: "JPG/PDF", cantidad: "4", notas: "Barra, salón, fachada y punto de recojo.", on: true },
        { id: "CN-MX-06", paquete: "Anteproyecto", etapa: "Desarrollo", entregable: "Cuadro referencial de acabados", formato: "PDF", cantidad: "1", notas: "Sujeto a selección de proveedores.", on: true },
      ],
      "excl.fe": "2026-07-16",
      "excl.resp": "Arq. Elena Mora",
      "excl.items": [
        { id: "CN-AL-01", cat: "Información pendiente", item: "Levantamiento del local", estado: "Revisión", mostrar: true, texto: "Alerta: falta completar y validar el levantamiento arquitectónico." },
        { id: "CN-AL-02", cat: "Información pendiente", item: "Coordinación de especialidades", estado: "Revisión", mostrar: true, texto: "Alerta: faltan criterios de electricidad, sanitarias, extracción y HVAC." },
        { id: "CN-AL-03", cat: "Información pendiente", item: "Equipamiento de cocina", estado: "Revisión", mostrar: true, texto: "Alerta: falta ficha técnica y medidas definitivas del equipamiento." },
        { id: "CN-AL-04", cat: "Información pendiente", item: "Licencias", estado: "Revisión", mostrar: true, texto: "Alerta: falta confirmar requisitos municipales, ITSE y permisos sanitarios." },
        { id: "CN-AL-05", cat: "Información pendiente", item: "Identidad gráfica", estado: "Revisión", mostrar: true, texto: "Alerta: falta recibir manual de marca, gráfica y señalética." },
        { id: "CN-AL-06", cat: "Información pendiente", item: "Proveedores", estado: "Revisión", mostrar: true, texto: "Alerta: falta definir proveedores de mobiliario, luminarias y acabados." },
        { id: "CN-EX-07", cat: "Exclusiones generales", item: "Gestión de licencias", estado: "Excluido", mostrar: true, texto: "La tramitación y el pago de derechos no forman parte del alcance base." },
      ],
      "cron.fe": "2026-07-16",
      "cron.inicio": "2026-07-20",
      "cron.etapas": [
        { id: "lev", label: "Levantamiento", color: "#2471A3", semanas: 1, activa: true },
        { id: "ant", label: "Anteproyecto", color: "#1E8449", semanas: 2, activa: true },
        { id: "des", label: "Desarrollo", color: "#B7950B", semanas: 3, activa: true },
        { id: "exp", label: "Coordinación y cierre", color: "#BA4A00", semanas: 2, activa: true },
        { id: "sup", label: "Supervisión / Obra", color: "#6C3483", semanas: 8, activa: false },
      ],
      "cron.honorario": "28600",
      "cron.nota": "Objetivo: expediente coordinado en 8 semanas. La fecha depende de cerrar las seis alertas de información.",
      "cron.hitosCobro": [
        { id: "adelanto", label: "Adelanto", pct: 50, when: "Al inicio", checked: true },
        { id: "anteproyecto", label: "Anteproyecto aprobado", pct: 25, when: "Fin de semana 3", checked: false },
        { id: "entrega", label: "Entrega coordinada", pct: 25, when: "Fin de semana 8", checked: false },
      ],
    },
  ),
  tourSteps: [
    { id: "cafe-brief", title: "Operación antes que forma", description: "Explora capacidad, barra, cocina y flujos de servicio en el brief.", toolId: "brief", track: "construccion" },
    { id: "cafe-matriz", title: "Entregables de interiorismo", description: "Revisa el paquete de anteproyecto y la información que aún debe levantarse.", toolId: "matrix", track: "diseno" },
    { id: "cafe-alertas", title: "Alertas visibles", description: "Detecta seis vacíos críticos antes de comprometer alcance, costo y fecha.", toolId: "excl", track: "diseno" },
    { id: "cafe-plazo", title: "Apertura en 8 semanas", description: "Comprueba cómo el cronograma conecta decisiones con la fecha objetivo.", toolId: "cron", track: "diseno" },
  ],
  highlights: ["Capacidad para 42 personas", "Barra, cocina y servicio", "6 alertas de información", "Cronograma de 8 semanas"],
};

const oficinasId: DemoProjectId = "oficinas-gotomarket";
const oficinasUpdatedAt = "2026-07-18T18:30:00.000Z";
const oficinasTracks = { diseno: false, construccion: true, seguimiento: true };

const oficinas: DemoProjectDefinition = {
  id: oficinasId,
  version: FIXTURE_VERSION,
  title: "Oficinas GoToMarket",
  subtitle: "Design-build · Obra en ejecución en 3 niveles",
  clientName: "GoToMarket Perú",
  location: "Lima",
  area: 470,
  currency: "PEN",
  displayStatus: "En ejecución",
  duplicateStatus: "Ganado",
  tracks: oficinasTracks,
  project: buildProject(oficinasId, {
    name: "Oficinas GoToMarket",
    type: "Oficinas · Design-build",
    location: "Lima",
    tracks: oficinasTracks,
    archived: false,
    commercialStatus: "Ganado",
    createdAt: "2026-05-20T14:00:00.000Z",
    updatedAt: oficinasUpdatedAt,
  }),
  snapshot: buildSnapshot(
    oficinasId,
    oficinasUpdatedAt,
    {
      client: "GoToMarket Perú",
      projectName: "Oficinas GoToMarket",
      location: "Lima · 3 niveles",
      code: "COT-GTM-012",
      currency: "PEN",
    },
    {
      "cot.step": 2,
      "cot.fe": "2026-05-20",
      "cot.categorias": ["Arquitectura", "Instalaciones", "Equipamiento", "Exteriores"],
      "cot.nextId": 9,
      "cot.partidas": [
        { id: 1, categoria: "Arquitectura", codPartida: "ARQ-01", descripcion: "Tabiquería drywall RF y acústica", und: "M2", cant: 620, manoObra: 24, materiales: 42, utilidadPct: 15, riesgoPct: 4 },
        { id: 2, categoria: "Arquitectura", codPartida: "ARQ-02", descripcion: "Pintura látex lavable en muros y cielos", und: "M2", cant: 1860, manoObra: 9, materiales: 8.5, utilidadPct: 14, riesgoPct: 3 },
        { id: 3, categoria: "Arquitectura", codPartida: "ARQ-03", descripcion: "Piso vinílico de alto tránsito", und: "M2", cant: 470, manoObra: 18, materiales: 76, utilidadPct: 16, riesgoPct: 4 },
        { id: 4, categoria: "Instalaciones", codPartida: "IE-01", descripcion: "Adecuación eléctrica, datos y tomacorrientes", und: "GLB", cant: 1, manoObra: 28500, materiales: 43800, utilidadPct: 15, riesgoPct: 6 },
        { id: 5, categoria: "Instalaciones", codPartida: "IL-01", descripcion: "Suministro e instalación de iluminación LED", und: "UND", cant: 142, manoObra: 38, materiales: 126, utilidadPct: 15, riesgoPct: 4 },
        { id: 6, categoria: "Equipamiento", codPartida: "EQ-01", descripcion: "Mobiliario fijo y estaciones de trabajo", und: "GLB", cant: 1, manoObra: 18200, materiales: 68500, utilidadPct: 17, riesgoPct: 5 },
        { id: 7, categoria: "Instalaciones", codPartida: "AC-01", descripcion: "Sistema de aire acondicionado y ventilación", und: "GLB", cant: 1, manoObra: 24600, materiales: 59200, utilidadPct: 14, riesgoPct: 7 },
        { id: 8, categoria: "Exteriores", codPartida: "AZ-01", descripcion: "Techado ligero de azotea", und: "M2", cant: 96, manoObra: 145, materiales: 285, utilidadPct: 16, riesgoPct: 8 },
      ],
      "cot.nCuenta": "191-0000123456",
      "cot.banco": "BCP",
      "cot.cci": "002-191-000012345678-10",
      "cot.ggPct": 8,
      "cot.supPct": 6,
      "cot.igvPct": 18,
      "cot.condPago": "30% adelanto, valorizaciones quincenales y 10% contra entrega",
      "cot.obs": "Precios en PEN. Vigencia 15 días. Trabajos coordinados por niveles para mantener operación parcial.",
      "obra.fe": "2026-06-01",
      "obra.inicio": "2026-06-08",
      "obra.resp": "Ing. Valeria Torres",
      "obra.obs": "Ejecución por frentes y niveles. Techado de azotea sujeto a la OC-01.",
      "obra.syncAt": "2026-07-18T18:00:00.000Z",
      "obra.nextId": 9,
      "obra.partidas": [
        { id: 1, sourceCotId: 1, categoria: "Arquitectura", codPartida: "ARQ-01", descripcion: "Tabiquería drywall RF y acústica", und: "M2", cant: 620, duracionDias: 15, predecesoraId: null, tipoDep: "FS", desfaseDias: 0, avancePct: 100 },
        { id: 2, sourceCotId: 4, categoria: "Instalaciones", codPartida: "IE-01", descripcion: "Adecuación eléctrica, datos y tomacorrientes", und: "GLB", cant: 1, duracionDias: 18, predecesoraId: 1, tipoDep: "SS", desfaseDias: 5, avancePct: 72 },
        { id: 3, sourceCotId: 7, categoria: "Instalaciones", codPartida: "AC-01", descripcion: "Aire acondicionado y ventilación", und: "GLB", cant: 1, duracionDias: 16, predecesoraId: 1, tipoDep: "SS", desfaseDias: 7, avancePct: 60 },
        { id: 4, sourceCotId: 2, categoria: "Arquitectura", codPartida: "ARQ-02", descripcion: "Pintura de muros y cielos", und: "M2", cant: 1860, duracionDias: 12, predecesoraId: 2, tipoDep: "FS", desfaseDias: 0, avancePct: 45 },
        { id: 5, sourceCotId: 3, categoria: "Arquitectura", codPartida: "ARQ-03", descripcion: "Piso vinílico de alto tránsito", und: "M2", cant: 470, duracionDias: 9, predecesoraId: 4, tipoDep: "SS", desfaseDias: 4, avancePct: 30 },
        { id: 6, sourceCotId: 5, categoria: "Instalaciones", codPartida: "IL-01", descripcion: "Instalación de iluminación LED", und: "UND", cant: 142, duracionDias: 8, predecesoraId: 4, tipoDep: "SS", desfaseDias: 3, avancePct: 24 },
        { id: 7, sourceCotId: 6, categoria: "Equipamiento", codPartida: "EQ-01", descripcion: "Mobiliario y estaciones de trabajo", und: "GLB", cant: 1, duracionDias: 14, predecesoraId: 5, tipoDep: "FS", desfaseDias: 0, avancePct: 10 },
        { id: 8, sourceCotId: 8, categoria: "Exteriores", codPartida: "AZ-01", descripcion: "Techado ligero de azotea", und: "M2", cant: 96, duracionDias: 12, predecesoraId: 3, tipoDep: "FS", desfaseDias: 2, avancePct: 0 },
      ],
      "val.view": "doc",
      "val.nv": "3",
      "val.per": "2026-W29",
      "val.fe": "2026-07-18",
      "val.est": "Borrador",
      "val.el": "Ing. Valeria Torres",
      "val.mc": 532137,
      "val.ad": 0,
      "val.de": 0,
      "val.pa": 159641,
      "val.nextId": 9,
      "val.parts": [
        { id: 1, cod: "ARQ-01", desc: "Tabiquería drywall RF y acústica", pre: 51546, ant: 43814, pct: 100 },
        { id: 2, cod: "IE-01", desc: "Adecuación eléctrica, datos y tomacorrientes", pre: 90284, ant: 43336, pct: 72 },
        { id: 3, cod: "AC-01", desc: "Aire acondicionado y ventilación", pre: 105326, ant: 36864, pct: 60 },
        { id: 4, cod: "ARQ-02", desc: "Pintura de muros y cielos", pre: 41875, ant: 8375, pct: 45 },
        { id: 5, cod: "ARQ-03", desc: "Piso vinílico de alto tránsito", pre: 55344, ant: 0, pct: 30 },
        { id: 6, cod: "IL-01", desc: "Iluminación LED", pre: 27815, ant: 0, pct: 24 },
        { id: 7, cod: "EQ-01", desc: "Mobiliario y estaciones", pre: 105828, ant: 0, pct: 10 },
        { id: 8, cod: "AZ-01", desc: "Techado ligero de azotea", pre: 54119, ant: 0, pct: 0 },
      ],
      "oc.cod": "OC-01",
      "oc.fe": "2026-07-17",
      "oc.sol": "Cliente",
      "oc.desc": "Techado de azotea",
      "oc.motivo": "Pedido del cliente",
      "oc.impacto": "Alcance + Plazo + Honorarios",
      "oc.estadoResolucion": "Pendiente",
      "oc.docsAfect": "Cotización, cronograma de obra, planos de azotea y valorizaciones",
      "oc.antesAlc": "Azotea abierta destinada a reuniones eventuales.",
      "oc.despAlc": "Cubierta ligera de 96 m² con estructura metálica, drenaje e iluminación.",
      "oc.antesEnt": "Planos de arquitectura e instalaciones interiores.",
      "oc.despEnt": "Planos y detalles de techado, estructura, drenaje e iluminación de azotea.",
      "oc.antesPlazo": "Entrega contractual: 31/07/2026.",
      "oc.despPlazo": "Entrega propuesta: 12/08/2026.",
      "oc.honorAd": "54119",
      "oc.extPlazo": "12 días calendario",
      "oc.nuevoTotal": "586256",
      "oc.hitoPago": "50% con aprobación y 50% en la instalación",
      "oc.obsKey": "No iniciar fabricación hasta recibir aprobación escrita y confirmar carga estructural.",
      "oc.ajusteCron": "Sí",
      "oc.notaCron": "Se incorpora un frente paralelo en azotea desde el 27/07/2026.",
      "oc.emiteNom": "Arq. Diego Salazar",
      "oc.emiteCargo": "Project Manager",
      "oc.emiteFe": "2026-07-17",
      "oc.apruebaNom": "Mariana Paredes",
      "oc.apruebaCargo": "Gerente de Administración",
      "oc.apruebaFe": "",
    },
  ),
  tourSteps: [
    { id: "gtm-cotizacion", title: "Cotización de obra", description: "Explora partidas, cantidades, costos, utilidad y riesgo de una obra realista.", toolId: "cot", track: "construccion" },
    { id: "gtm-cronograma", title: "Obra por frentes", description: "Revisa dependencias y avance de drywall, instalaciones, acabados y equipamiento.", toolId: "cronobra", track: "construccion" },
    { id: "gtm-valorizacion", title: "Valorización de avance", description: "Comprueba el avance anterior y actual que sustenta el cobro al cliente.", toolId: "val", track: "seguimiento" },
    { id: "gtm-cambio", title: "Cambio controlado", description: "Abre la orden de cambio “Techado de azotea” con impacto en alcance, costo y plazo.", toolId: "oc", track: "seguimiento" },
  ],
  highlights: ["470 m² en 3 niveles", "8 partidas con costos y margen", "Cronograma de obra", "Valorización de avance", "OC: Techado de azotea"],
};

export const DEMO_DEFINITIONS: readonly DemoProjectDefinition[] = Object.freeze([
  casaLadera,
  cafeNerea,
  oficinas,
]);

export const getDemoDefinition = (id: DemoProjectId) => (
  DEMO_DEFINITIONS.find((definition) => definition.id === id)
);
